# Generated by Django 4.2.1 on 2023-08-18 09:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='Ism')),
                ('yosh', models.PositiveSmallIntegerField(default=0, verbose_name='Yoshi')),
                ('batafsil', models.TextField(verbose_name='Batafsil')),
                ('image', models.FileField(upload_to='actors/', verbose_name='Rasmi')),
            ],
            options={
                'verbose_name': 'Aktyor yoki rejissor',
                'verbose_name_plural': 'Aktyorlar va rejissorlar',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100, verbose_name='Nomi')),
                ('haqida', models.TextField(verbose_name='Film haqida')),
                ('rasmi', models.FileField(upload_to='movies/', verbose_name='Rasmi')),
                ('yili', models.PositiveSmallIntegerField(default=2019, verbose_name='Olingan yili')),
                ('mamlakat', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='sayitga_joylangan')),
                ('aktyorlar', models.ManyToManyField(related_name='film_actor', to='uzflix.aktyor', verbose_name='aktiyor')),
            ],
            options={
                'verbose_name': 'Filim',
                'verbose_name_plural': 'Filimlar',
            },
        ),
        migrations.CreateModel(
            name='Janr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('jangari', 'JANGARI'), ('fantastika', 'FANTASTIKA'), ('oilaviy', 'OILAVIY')], max_length=100, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=283)),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
            },
        ),
        migrations.CreateModel(
            name='Izoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField(max_length=1000, verbose_name='Matn')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzflix.film', verbose_name='film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Izoh',
                'verbose_name_plural': 'Izoh',
            },
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='uzflix.janr', verbose_name='janrlar'),
        ),
        migrations.AddField(
            model_name='film',
            name='rejissorlar',
            field=models.ManyToManyField(related_name='film_director', to='uzflix.aktyor', verbose_name='rejissor'),
        ),
        migrations.CreateModel(
            name='Baho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzflix.film', verbose_name='film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reting',
                'verbose_name_plural': 'Ratinglar',
            },
        ),
    ]
