# Generated by Django 4.2.1 on 2023-08-21 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzflix', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aktyor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='film',
            name='rasmi',
        ),
        migrations.RemoveField(
            model_name='film',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='janr',
            name='slug',
        ),
    ]
